export const ACTION_TYPES = {
    SET_FILTER_DATA: 'SET_FILTER_DATA',
    SET_SELECTED_FILTERS: 'SET_SELECTED_FILTERS',
    SET_FILTER_LOADING: 'SET_FILTER_LOADING',
    SET_PRODUCTS_DATA: 'SET_PRODUCTS_DATA',
    SET_PRODUCTS_LOADING: 'SET_PRODUCTS_LOADING'
};